version: '3.7'

services:
  app:
    image: nginx:1.16.1
    container_name: app
    ports:
      - "8888:80"
    volumes:
    - ./src:/var/www/html
    - ./conf/app/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

